# Generated by Django 3.2.8 on 2021-10-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='template_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
